### PR TITLE
Avoids changing the mutator when there's only one.

### PR DESCRIPTION
**Pull request by hadi88**
Otherwise, it could cause a check failure.

### CODE REVIEW

**Comment by fmeum** [comment]
@hadi88 Which type did you observe the issue with? I could add a test.

**Comment by hadi88** [comment]
This may not be the best fix. Feel free to drop the PR if you find out what's the root cause.

I used a dynamic protobuf with the following structure:
dynami_proto {
  inner_normal_proto { string_field }
}

And I observed the following crash (line numbers could be different from the main branch):

	at com.code_intelligence.jazzer.mutation.support.Preconditions.require(Preconditions.java:38)
	at com.code_intelligence.jazzer.mutation.engine.SeededPseudoRandom.closedRange(SeededPseudoRandom.java:95)
	at com.code_intelligence.jazzer.mutation.engine.SeededPseudoRandom.otherIndexIn(SeededPseudoRandom.java:85)
	at com.code_intelligence.jazzer.mutation.engine.SeededPseudoRandom.otherIndexIn(SeededPseudoRandom.java:80)
	at com.code_intelligence.jazzer.mutation.combinator.MutatorCombinators$10.mutateInPlace(MutatorCombinators.java:297)
	at com.code_intelligence.jazzer.mutation.combinator.MutatorCombinators$4.mutateInPlace(MutatorCombinators.java:149)
	at com.code_intelligence.jazzer.mutation.combinator.MutatorCombinators$DelegatingSerializingInPlaceMutator.mutateInPlace(MutatorCombinators.java:375)
	at com.code_intelligence.jazzer.mutation.api.SerializingInPlaceMutator.mutate(SerializingInPlaceMutator.java:67)
	at com.code_intelligence.jazzer.mutation.combinator.PostComposedMutator.mutate(PostComposedMutator.java:56)
	at com.code_intelligence.jazzer.mutation.mutator.lang.NullableMutatorFactory$NullableMutator.mutate(NullableMutatorFactory.java:93)
	at com.code_intelligence.jazzer.mutation.combinator.ProductMutator.mutateInPlace(ProductMutator.java:99)
	at com.code_intelligence.jazzer.mutation.combinator.ProductMutator.mutateInPlace(ProductMutator.java:37)
	at com.code_intelligence.jazzer.mutation.api.SerializingInPlaceMutator.mutate(SerializingInPlaceMutator.java:67)
	at com.code_intelligence.jazzer.mutation.ArgumentsMutator.mutate(ArgumentsMutator.java:180)
	at com.code_intelligence.jazzer.mutation.ArgumentsMutator.mutate(ArgumentsMutator.java:173)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.mutateOne(FuzzTargetRunner.java:308)
	at com.code_intelligence.jazzer.runtime.FuzzTargetRunnerNatives.startLibFuzzer(Native Method)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:464)
	at com.code_intelligence.jazzer.driver.FuzzTargetRunner.startLibFuzzer(FuzzTargetRunner.java:341)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:132)
	at com.code_intelligence.jazzer.Jazzer.start(Jazzer.java:181)
	at com.code_intelligence.jazzer.Jazzer.main(Jazzer.java:131)

**Comment by fmeum** [comment]
@hadi88 I added a test case that reproduced the failure, but it relies on `oneof`. I couldn't find one that doesn't, but it's definitely the right fix for this one. Thanks!

**Comment by hadi88** [comment]
Thanks for looking into this.

Sorry! That was my mistake. The test case indeed includes a oneof:

dynamic_proto {
  oneof oneof_block {
    inner_normal_proto { string_field }
  }
}

**Pull request merged**
