### PR TITLE
bazel: Fix build on arm64 macOS without Rosetta

### PR DESCRIPTION
**Pull request by fmeum**
Ref: CLI-547

### CODE REVIEW

**Comment by fmeum** [comment]
@MarkusZoppelt Could you try building with this PR? It does seem to be very difficult to uninstall Rosetta without going through recovery, so I unfortunately can't test this myself.

**Comment by fmeum** [comment]
@MarkusZoppelt Could you try again with the version I just force-pushed? I messed up the toolchain definition on the first try.

**Comment by MarkusZoppelt** [comment]
@fmeum Is this expected bahaviour?

```
$ bazel build //:jazzer_release

Starting local Bazel server and connecting to it...
INFO: Analyzed target //:jazzer_release (121 packages loaded, 1976 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_mz/6b6d52b1f712bd386568d1d984781c98/external/remote_java_tools/BUILD:162:10: Linking external/remote_java_tools/ijar_cc_binary failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/remote_java_tools/ijar_cc_binary-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang-15: error: invalid linker name in argument '-fuse-ld=-debugger-tuning=lldb'
Target //:jazzer_release failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/mz/code/jazzer/driver/src/main/java/com/code_intelligence/jazzer/BUILD.bazel:10:13 Building driver/src/main/java/com/code_intelligence/jazzer/libjazzer_lib.jar (1 source file) failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/remote_java_tools/ijar_cc_binary-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 20.779s, Critical Path: 1.66s
INFO: 105 processes: 71 internal, 32 darwin-sandbox, 2 local.
FAILED: Build did NOT complete successfully
```

**Comment by fmeum** [comment]
@MarkusZoppelt *Expected* yes, *desired* no ;-) I know what's up with that, more recent versions of macOS lld seem to require a newer version of Bazel than we are currently using. I will update and rebase this PR.

**Review by bertschneider — APPROVED** [review]

**Comment by fmeum** [comment]
I will include a workaround for the remaining, separate issue in https://github.com/CodeIntelligenceTesting/jazzer/pull/504 in case it isn't fixed upstream in time.

**Review by MarkusZoppelt — COMMENTED** [review]
Works!

**Pull request merged**
